### ISSUE TITLE
Requires a peer of Json5

### ISSUE THREAD

**Issue by michaelryancaputo** [seeden/react-form-controlled#8]
Hey there, I keep getting the error `json5-loader@0.6.0 requires a peer of json5@>= 0.2.0 < 0.5 but none was installed.`, have tried to install json5 manually, and continue to get the same error.

Is this a known issue?

**Comment by seeden** [comment]
I can not see this issue with latest version. Please verify it

**Comment by michaelryancaputo** [comment]
Sorry i've moved on since posting this and likely won't have a chance to reproduce it any time soon. going to close the issue.
